# Generated by Django 4.1 on 2022-09-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0003_remove_review_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
    ]
