# Generated by Django 4.1 on 2022-10-14 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0005_review_ticket_ticket_time_created_ticket_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='flux.ticket'),
            preserve_default=False,
        ),
    ]
