# Generated by Django 4.1 on 2022-10-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0007_remove_review_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(default=1, blank=True, on_delete=django.db.models.deletion.CASCADE, to='flux.ticket')
        ),
    ]
