# Generated by Django 4.1 on 2022-10-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0008_alter_review_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='flux.ticket'),
        ),
    ]
