# Generated by Django 4.1 on 2022-09-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("CREATOR", "Créateur"), ("SUBSCRIBER", "Abonné")],
                default="",
                max_length=30,
                verbose_name="Rôle",
            ),
            preserve_default=False,
        ),
    ]
