# Generated by Django 4.1 on 2022-09-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="book_photo",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        ),
    ]
